// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADyVjDe-xV3NdUhTuV33uDuBH-whLOG3E',
    appId: '1:60986795022:web:b6c7b5dbaaafa8c249c85f',
    messagingSenderId: '60986795022',
    projectId: 'myosa-c3e89',
    authDomain: 'myosa-c3e89.firebaseapp.com',
    storageBucket: 'myosa-c3e89.appspot.com',
    measurementId: 'G-8Z2W4EMJPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBruzo5kWQnpGWHXzUswDA1l47td_RpCdg',
    appId: '1:60986795022:android:7f00f25964130c9749c85f',
    messagingSenderId: '60986795022',
    projectId: 'myosa-c3e89',
    storageBucket: 'myosa-c3e89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCtRdFOXUc7p0Abbp8LRWHIHXyw2gfe3A',
    appId: '1:60986795022:ios:8a14615e55d4275449c85f',
    messagingSenderId: '60986795022',
    projectId: 'myosa-c3e89',
    storageBucket: 'myosa-c3e89.appspot.com',
    iosBundleId: 'com.example.myosa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCtRdFOXUc7p0Abbp8LRWHIHXyw2gfe3A',
    appId: '1:60986795022:ios:6f75a88f866aabe249c85f',
    messagingSenderId: '60986795022',
    projectId: 'myosa-c3e89',
    storageBucket: 'myosa-c3e89.appspot.com',
    iosBundleId: 'com.example.myosa.RunnerTests',
  );
}
